### ISSUE TITLE
Static Website

### ISSUE THREAD

**Issue by Itzbenz** [shadow01148/webwebweb#12]
This site is read-only and there is no need for interactivity

**Comment by Itzbenz** [comment]
https://dev.to/robertobutti/how-to-start-building-your-static-website-with-svelte-and-tailwindcss-hbk

**Comment by shadow01148** [comment]
![image](https://user-images.githubusercontent.com/76457846/212846277-56a70cb0-13f4-4b9f-a4e8-899aae9d735b.png)

**Comment by shadow01148** [comment]
fault on my end, fixed
